module.exports = {
 HANDLE_FETCH_DATA: 'handle-fetch-data',
  FETCH_DATA_FROM_STORAGE: 'fetch-data-from-storage',
  HANDLE_SAVE_DATA: 'handle-save-data',
  SAVE_DATA_IN_STORAGE: 'save-data-in-storage',
  REMOVE_DATA_FROM_STORAGE: 'remove-data-from-storage',
  HANDLE_REMOVE_DATA: 'handle-remove-data',
  EDIT_DATA_IN_STORAGE: 'edit-data-in-storage',
  categories: [
    'Athletics',
    'Bar & Restaurant',
    'Beauty',
    'Bills',
    'Car',
    'Clothes',
    'Education',
    'Entertainment',
    'Food',
    'Garden & Yard',
    'Gifts',
    'Health',
    'Home',
    'Pets',
    'Savings',
    'Technology',
    'Toiletries',
    'Transportation',
    'Travel',
    'Other',
  ]
}
